INSERT INTO Address VALUES 
(default, 'Comanche', 'Miami', 'Florida', 33129),
(default, 'Kings', 'Saint Paul', 'Minnesota', 55103),
(default, 'Packers', 'Beaufort', 'South Carolina', 29905),
(default, 'Columbus', 'Des Moines', 'Iowa', 50310),
(default, 'Montana', 'New Orleans', 'Louisiana', 70183),
(default, 'Holy Cross', 'Irvine', 'California', 92612),
(default, 'Swallow', 'Corpus Christi', 'Texas', 78426),
(default, 'Garrison', 'Vero Beach', 'Florida', 32964),
(default, 'Vernon', 'Bronx', 'New York', 10459),
(default, '4th', 'Birmingham', 'Alabama', 35220),
(default, 'Swallow', 'Portland', 'Oregon', 97216),
(default, 'Riverside', 'Bowie', 'Maryland', 20719),
(default, 'Starling', 'Hot Springs National Park', 'Arkansas', 71914),
(default, 'Colorado', 'Springfield', 'Illinois', 62776),
(default, 'Nelson', 'Chicago', 'Illinois', 60619),
(default, 'Butternut', 'Inglewood', 'California', 90305),
(default, 'Golf Course', 'Washington', 'District of Columbia', 20088),
(default, 'Comanche', 'Aiken', 'South Carolina', 29805),
(default, '6th', 'Jacksonville', 'Florida', 32244),
(default, 'Annamark', 'Austin', 'Texas', 78789),
(default, 'Dorton', 'Columbus', 'Georgia', 31904),
(default, 'Thackeray', 'Columbus', 'Ohio', 43210),
(default, 'Beilfuss', 'Saint Paul', 'Minnesota', 55188),
(default, 'Moland', 'Spartanburg', 'South Carolina', 29319),
(default, 'Gateway', 'Newark', 'New Jersey', 07112),
(default, 'Merchant', 'Chicago', 'Illinois', 60630),
(default, 'South', 'Huntsville', 'Alabama', 35895),
(default, 'Sheridan', 'Saint Augustine', 'Florida', 32092),
(default, 'Sachs', 'South Bend', 'Indiana', 46634),
(default, 'Fairview', 'Mesa', 'Arizona', 85205),
(default, 'Jana', 'Seattle', 'Washington', 98127),
(default, 'Hansons', 'Charleston', 'South Carolina', 29416),
(default, 'Donald', 'El Paso', 'Texas', 79911),
(default, 'Carey', 'Marietta', 'Georgia', 30066),
(default, 'Swallow', 'Waterbury', 'Connecticut', 06705),
(default, 'Mendota', 'Englewood', 'Colorado', 80150),
(default, 'Brown', 'Kansas City', 'Missouri', 64193),
(default, 'Grover', 'Santa Barbara', 'California', 93150),
(default, 'Brickson Park', 'Atlanta', 'Georgia', 30380),
(default, 'Sunnyside', 'Akron', 'Ohio', 44310),
(default, 'Pleasure', 'Newark', 'New Jersey', 07112),
(default, 'Glendale', 'Denton', 'Texas', 76210),
(default, 'Manley', 'Baltimore', 'Maryland', 21275),
(default, 'Killdeer', 'Jackson', 'Mississippi', 39216),
(default, 'Sachs', 'Kansas City', 'Missouri', 64149),
(default, 'Dakota', 'Huntington', 'West Virginia', 25711),
(default, 'Daystar', 'Washington', 'District of Columbia', 20414),
(default, 'Scott', 'Newton', 'Massachusetts', 02162),
(default, 'Caliangt', 'Knoxville', 'Tennessee', 37919),
(default, 'Dawn', 'Tucson', 'Arizona', 85754),
(default, 'South', 'Brooklyn', 'New York', 11225),
(default, 'Hansons', 'Hampton', 'Virginia', 23663),
(default, 'Becker', 'Lansing', 'Michigan', 48912),
(default, 'Charing Cross', 'Peoria', 'Illinois', 61651),
(default, 'Rusk', 'Stamford', 'Connecticut', 06912),
(default, 'Londonderry', 'Tyler', 'Texas', 75799),
(default, 'Marcy', 'Atlanta', 'Georgia', 31196),
(default, 'Transport', 'Washington', 'District of Columbia', 20299),
(default, 'Quincy', 'San Francisco', 'California', 94110),
(default, 'Hoffman', 'Winston Salem', 'North Carolina', 27150),
(default, 'Commercial', 'Oakland', 'California', 94660),
(default, 'Shoshone', 'Springfield', 'Massachusetts', 01105),
(default, 'Shelley', 'Washington', 'District of Columbia', 20244),
(default, 'Hayes', 'Shreveport', 'Louisiana', 71151),
(default, 'Stoughton', 'Pittsburgh', 'Pennsylvania', 15250),
(default, 'Morrow', 'Lansing', 'Michigan', 48930),
(default, 'Sauthoff', 'Tucson', 'Arizona', 85715),
(default, 'Butternut', 'Rochester', 'New York', 14683),
(default, 'Kedzie', 'Charlotte', 'North Carolina', 28230),
(default, 'High Crossing', 'San Antonio', 'Texas', 78240),
(default, 'Dunning', 'Elizabeth', 'New Jersey', 07208),
(default, 'Aberg', 'Raleigh', 'North Carolina', 27621),
(default, 'Sunfield', 'Lynchburg', 'Virginia', 24503),
(default, 'Ramsey', 'Spring', 'Texas', 77388),
(default, 'Vahlen', 'Charleston', 'West Virginia', 25321),
(default, 'Texas', 'Huntsville', 'Alabama', 35810),
(default, 'David', 'Raleigh', 'North Carolina', 27605),
(default, 'Moulton', 'Phoenix', 'Arizona', 85099),
(default, 'Huxley', 'Detroit', 'Michigan', 48242),
(default, 'Crest Line', 'Orange', 'California', 92867),
(default, 'Havey', 'Oklahoma City', 'Oklahoma', 73197),
(default, 'Anniversary', 'Albuquerque', 'New Mexico', 87195),
(default, 'Southridge', 'Pasadena', 'California', 91125),
(default, 'Dennis', 'San Francisco', 'California', 94126),
(default, 'Sutherland', 'Detroit', 'Michigan', 48224),
(default, 'Bonner', 'Charlotte', 'North Carolina', 28284),
(default, 'Ohio', 'Atlanta', 'Georgia', 31106),
(default, 'Butternut', 'Jackson', 'Mississippi', 39296),
(default, 'Sherman', 'Seattle', 'Washington', 98121),
(default, 'Prentice', 'Wilkes Barre', 'Pennsylvania', 18706),
(default, 'Badeau', 'Roanoke', 'Virginia', 24020),
(default, 'Gateway', 'Inglewood', 'California', 90310),
(default, 'Sycamore', 'Arvada', 'Colorado', 80005),
(default, 'Dapin', 'Dallas', 'Texas', 75241),
(default, 'School', 'Houston', 'Texas', 77095),
(default, 'Manley', 'Birmingham', 'Alabama', 35205),
(default, 'Fieldstone', 'Evansville', 'Indiana', 47705),
(default, 'Rieder', 'Salt Lake City', 'Utah', 84115),
(default, 'Ridgeview', 'Marietta', 'Georgia', 30066),
(default, 'Twin Pines', 'Honolulu', 'Hawaii', 96840),
(default, 'Glendale', 'Cincinnati', 'Ohio', 45296),
(default, 'Russell', 'Fredericksburg', 'Virginia', 22405),
(default, 'Mifflin', 'Lake Charles', 'Louisiana', 70607),
(default, 'Hanover', 'Little Rock', 'Arkansas', 72215),
(default, 'Cottonwood', 'Monticello', 'Minnesota', 55590),
(default, 'Union', 'Pittsburgh', 'Pennsylvania', 15215),
(default, 'Carpenter', 'Portsmouth', 'New Hampshire', 03804),
(default, 'Grim', 'Pasadena', 'California', 91103),
(default, 'North', 'Springfield', 'Illinois', 62718),
(default, 'Myrtle', 'Cedar Rapids', 'Iowa', 52410),
(default, 'Ruskin', 'Los Angeles', 'California', 90045),
(default, 'Moland', 'Charlottesville', 'Virginia', 22903),
(default, 'South', 'Albuquerque', 'New Mexico', 87140),
(default, 'Bluestem', 'Boston', 'Massachusetts', 02298),
(default, 'Truax', 'Corpus Christi', 'Texas', 78426),
(default, 'Arizona', 'Springfield', 'Illinois', 62776),
(default, 'Milwaukee', 'El Paso', 'Texas', 88553),
(default, 'Katie', 'Springfield', 'Illinois', 62776),
(default, 'Pawling', 'Washington', 'District of Columbia', 20244),
(default, 'Westerfield', 'Sacramento', 'California', 94257),
(default, 'Bobwhite', 'San Francisco', 'California', 94137),
(default, 'Mosinee', 'Fort Worth', 'Texas', 76121),
(default, 'Merry', 'New York City', 'New York', 10115),
(default, 'Atwood', 'Washington', 'District of Columbia', 20337),
(default, 'Vernon', 'Pasadena', 'California', 91103),
(default, 'Clemons', 'New Haven', 'Connecticut', 06505),
(default, 'Fordem', 'Washington', 'District of Columbia', 20557),
(default, 'Menomonie', 'Escondido', 'California', 92030),
(default, '1st', 'Brooklyn', 'New York', 11210),
(default, 'Lotheville', 'Manchester', 'New Hampshire', 03105),
(default, 'Crowley', 'Southfield', 'Michigan', 48076),
(default, 'Calypso', 'Minneapolis', 'Minnesota', 55458),
(default, 'Waubesa', 'Gastonia', 'North Carolina', 28055),
(default, 'Thackeray', 'Fargo', 'North Dakota', 58106),
(default, 'Fairfield', 'Lafayette', 'Louisiana', 70593),
(default, 'Bartillon', 'Dearborn', 'Michigan', 48126),
(default, 'Ronald Regan', 'Fairfax', 'Virginia', 22036),
(default, 'Kennedy', 'Huntington', 'West Virginia', 25770),
(default, 'Farragut', 'Philadelphia', 'Pennsylvania', 19141),
(default, 'Blue Bill Park', 'Richmond', 'Virginia', 23228),
(default, 'Rowland', 'Tampa', 'Florida', 33615),
(default, 'Dryden', 'Brooklyn', 'New York', 11247),
(default, '1st', 'Tucson', 'Arizona', 85720),
(default, 'Calypso', 'Mesa', 'Arizona', 85205),
(default, 'Manufacturers', 'Wichita', 'Kansas', 67236),
(default, 'Spenser', 'Boulder', 'Colorado', 80305),
(default, 'Buena Vista', 'Newark', 'New Jersey', 07112),
(default, 'Raven', 'Fort Wayne', 'Indiana', 46825),
(default, 'Carpenter', 'Chicago', 'Illinois', 60657),
(default, 'Larry', 'Mc Keesport', 'Pennsylvania', 15134),
(default, 'Ridgeway', 'Colorado Springs', 'Colorado', 80940),
(default, 'Eastlawn', 'Wilmington', 'Delaware', 19886),
(default, 'Thackeray', 'Gary', 'Indiana', 46406),
(default, 'Coleman', 'El Paso', 'Texas', 79955),
(default, 'Meadow Ridge', 'Silver Spring', 'Maryland', 20918),
(default, 'Service', 'Denver', 'Colorado', 80243),
(default, 'Loeprich', 'Huntington Beach', 'California', 92648),
(default, 'Green', 'El Paso', 'Texas', 88569),
(default, 'Burning Wood', 'Schenectady', 'New York', 12305),
(default, 'Tomscot', 'Missoula', 'Montana', 59806),
(default, 'Red Cloud', 'New York City', 'New York', 10131),
(default, 'Vermont', 'Denver', 'Colorado', 80217),
(default, 'Fairview', 'San Antonio', 'Texas', 78230),
(default, 'Heffernan', 'Fresno', 'California', 93726),
(default, 'Heath', 'Chicago', 'Illinois', 60669),
(default, 'Everett', 'Little Rock', 'Arkansas', 72231),
(default, 'Cody', 'Flint', 'Michigan', 48505),
(default, 'Riverside', 'Atlanta', 'Georgia', 31119),
(default, 'Oakridge', 'Tucson', 'Arizona', 85720),
(default, 'Susan', 'Dallas', 'Texas', 75226),
(default, 'Namekagon', 'Scottsdale', 'Arizona', 85260),
(default, 'Graceland', 'Dallas', 'Texas', 75353),
(default, 'Ridgeview', 'Springfield', 'Massachusetts', 01129),
(default, 'Meadow Vale', 'Irving', 'Texas', 75037),
(default, 'Dunning', 'Washington', 'District of Columbia', 20062),
(default, 'Memorial', 'Los Angeles', 'California', 90071),
(default, 'Pine View', 'San Antonio', 'Texas', 78240),
(default, 'Hoffman', 'Panama City', 'Florida', 32412),
(default, 'Hoffman', 'Oakland', 'California', 94611),
(default, 'Buell', 'Atlanta', 'Georgia', 30392),
(default, 'Paget', 'Van Nuys', 'California', 91406),
(default, 'Lunder', 'Evansville', 'Indiana', 47747),
(default, 'Meadow Valley', 'Baton Rouge', 'Louisiana', 70826),
(default, 'Goodland', 'Duluth', 'Georgia', 30096),
(default, 'Green Ridge', 'Milwaukee', 'Wisconsin', 53263),
(default, 'Ridgeview', 'Akron', 'Ohio', 44315),
(default, 'Homewood', 'Reno', 'Nevada', 89505),
(default, 'Ridgeview', 'Cambridge', 'Massachusetts', 02142),
(default, 'Sage', 'Sarasota', 'Florida', 34233),
(default, 'Northland', 'Minneapolis', 'Minnesota', 55436),
(default, 'Division', 'Tulsa', 'Oklahoma', 74103),
(default, 'Village Green', 'Irvine', 'California', 92619),
(default, 'Chive', 'Toledo', 'Ohio', 43656),
(default, 'Cordelia', 'New York City', 'New York', 10090),
(default, 'Oak', 'Inglewood', 'California', 90305),
(default, 'Bonner', 'New York City', 'New York', 10160),
(default, 'Charing Cross', 'Jamaica', 'New York', 11407),
(default, 'Hazelcrest', 'Huntington', 'West Virginia', 25709),
(default, 'Texas', 'Wichita', 'Kansas', 67260),
(default, 'Emmet', 'Colorado Springs', 'Colorado', 80930);
