INSERT INTO Restaurant VALUES 
(default, 'Gutkowski Coffee Shop', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '12pm-10pm', 1),
(default, 'Corkery-Lueilwitz', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '11am - 9pm', 2),
(default, 'Pfeffer, Hauck and Carroll', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '1pm-3am', 3),
(default, 'Kilback Diner', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '9am - 9pm', 4),
(default, 'Strosin, Kessler and Kertzmann', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2pm-3am', 5),
(default, 'Senger, Grimes and Jacobs', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '1pm-3am', 6),
(default, 'Orn-Weissnat', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '12pm-10pm', 7),
(default, 'Gerlach Tavern', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '1pm-3pm', 8),
(default, 'Predovic, Berge and Sauer', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '12pm-10pm', 9),
(default, 'Hagenes Tavern', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '8am-11:59am', 10),
(default, 'Beahan Diner', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '12pm-11:59pm', 11),
(default, 'Torphy Coffee Shop', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis.', '2pm-3am', 12),
(default, 'Gislason Coffee Shop', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '11am - 9pm', 13),
(default, 'Schuppe Cafe', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '12am-8am', 14),
(default, 'McClure, Daugherty and Murphy', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '4am - 8pm', 15),
(default, 'Walsh-Grant', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '11am - 9pm', 16),
(default, 'Cormier-Daugherty', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '7am-11am', 17),
(default, 'Kerluke Coffee Shop', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '5pm-11am', 18),
(default, 'Russel-Conroy', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '11am - 9pm', 19),
(default, 'Gottlieb Cafe', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '12:30pm-11:30pm', 20),
(default, 'Powlowski Tavern', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '6am-11:30am', 21),
(default, 'Goodwin, Langosh and Bernhard', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2pm-3am', 22),
(default, 'Carroll-Stehr', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '11am - 9pm', 23),
(default, 'Reichert, Hintz and Gerlach', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '1pm-3am', 24),
(default, 'Douglas-Emmerich', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '7am-11am', 25),
(default, 'Hills Coffee Shop', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '12pm-11:59pm', 26),
(default, 'Bergnaum Coffee Shop', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '12pm-10pm', 27),
(default, 'Stracke, Kreiger and Dare', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2am - 6pm', 28),
(default, 'Auer, McCullough and Ebert', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '12am-8am', 29),
(default, 'Tremblay, Doyle and Feeney', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '12am-8am', 30),
(default, 'O''Kon-Klein', 'Fusce consequat. Nulla nisl. Nunc nisl.', '12am-8am', 31),
(default, 'Kulas-Haag', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '7am-11am', 32),
(default, 'Jakubowski-Rice', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '4am - 8pm', 33),
(default, 'Wisoky-Russel', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '6am-11:30am', 34),
(default, 'Corkery Tavern', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '12:30pm-11:30pm', 35),
(default, 'Renner Diner', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2am - 6pm', 36),
(default, 'Feil-Kautzer', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '12pm-11:59pm', 37),
(default, 'Mosciski, Cremin and Abbott', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '11am - 9pm', 38),
(default, 'Dickens-Deckow', 'Fusce consequat. Nulla nisl. Nunc nisl.', '12pm-11:59pm', 39),
(default, 'Russel, Casper and Prosacco', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '12pm-10pm', 40),
(default, 'Barton-Bradtke', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '6am-11:30am', 41),
(default, 'Renner-Oberbrunner', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '3pm-1am', 42),
(default, 'Prohaska, Jerde and Kshlerin', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '7pm-7am', 43),
(default, 'Larson Tavern', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.', '8am-11:59am', 44),
(default, 'Davis, Kilback and Pouros', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '6am-11:30am', 45),
(default, 'Shanahan, Schulist and Fisher', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '9am - 9pm', 46),
(default, 'Tromp, Zboncak and O''Hara', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '10am - 10pm', 47),
(default, 'Strosin, Koss and Corwin', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '1pm-3pm', 48),
(default, 'Mueller-Block', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2am - 6pm', 49),
(default, 'Strosin and Sons Grill', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '5pm-11:30pm', 50),
(default, 'Schamberger-Abbott', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '3pm-1am', 51),
(default, 'Weissnat Cafe', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '7pm-7am', 52),
(default, 'Bernhard, Weimann and Nienow', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '1pm-3am', 53),
(default, 'Steuber, Koepp and Glover', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '7am-11am', 54),
(default, 'O''Connell Cafe', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '12pm-10pm', 55),
(default, 'Brakus and Sons Grill', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '10am - 10pm', 56),
(default, 'Paucek, Wyman and Runolfsson', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '3pm-1am', 57),
(default, 'Cormier Cafe', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '8am-11:59am', 58),
(default, 'West Cafe', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2pm-3am', 59),
(default, 'Hoppe, Cartwright and Pollich', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '4am - 8pm', 60),
(default, 'Wiza Tavern', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '1pm-3am', 61),
(default, 'Streich-Torphy', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '12pm-10pm', 62),
(default, 'Harber, Reynolds and Walker', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '9am - 9pm', 63),
(default, 'Keeling-Cummerata', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '11am - 9pm', 64),
(default, 'Luettgen, McDermott and Ledner', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '6am-11:30am', 65),
(default, 'Schumm-O''Reilly', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '7am-11am', 66),
(default, 'Boyle and Sons Grill', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '7am-11am', 67),
(default, 'Homenick and Daughters Grill', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '5pm-11:30pm', 68),
(default, 'Hilll, Abbott and Gottlieb', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '12pm-10pm', 69),
(default, 'Hills-Effertz', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '12am-8am', 70),
(default, 'Hills, Lakin and Flatley', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '10am - 10pm', 71),
(default, 'McGlynn-Stamm', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '7pm-7am', 72),
(default, 'Huels Cafe', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '4am - 8pm', 73),
(default, 'Skiles-Ebert', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2pm-3am', 74),
(default, 'Blanda, Hegmann and Monahan', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.', '12:30pm-11:30pm', 75),
(default, 'O''Keefe, Douglas and Hayes', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '1pm-3pm', 76),
(default, 'Macejkovic, Kessler and Gerhold', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '6am-11:30am', 77),
(default, 'Williamson Tavern', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '12pm-10pm', 78),
(default, 'Hettinger and Daughters Grill', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '12pm-10pm', 79),
(default, 'Hilll, Schiller and O''Hara', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '5pm-11am', 80),
(default, 'Hayes-Kshlerin', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '4am - 8pm', 81),
(default, 'Wolff-Torphy', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '12pm-10pm', 82),
(default, 'Mohr, Jast and Oberbrunner', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '12pm-11:59pm', 83),
(default, 'Lakin, Hickle and Reilly', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '12am-8am', 84),
(default, 'Turcotte Diner', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '11am - 9pm', 85),
(default, 'Greenfelder, Spencer and Stroman', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '12pm-10pm', 86),
(default, 'Dare-VonRueden', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2am - 6pm', 87),
(default, 'Muller, Ebert and Lowe', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '6am-11:30am', 88),
(default, 'Ward Tavern', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '8am-11:59am', 89),
(default, 'Jerde-Hickle', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2pm-3am', 90),
(default, 'Buckridge, Beatty and Lueilwitz', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '3pm-1am', 91),
(default, 'Kreiger-Collins', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '7am-11am', 92),
(default, 'Johnson, Schinner and Tremblay', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '12am-8am', 93),
(default, 'Nikolaus, Renner and Buckridge', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '10am - 10pm', 94),
(default, 'Collier and Daughters Grill', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2pm-3am', 95),
(default, 'Hackett Diner', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '8am-11:59am', 96),
(default, 'Bartell, Becker and Quitzon', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '4am - 8pm', 97),
(default, 'Pacocha Cafe', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2pm-3am', 98),
(default, 'Corwin, Macejkovic and Hermann', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2am - 6pm', 99),
(default, 'Wiza, Krajcik and Terry', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '11am - 9pm', 100),
(default, 'Gulgowski Tavern', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '8am-11:59am', 101),
(default, 'Turcotte Cafe', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '5pm-11am', 102),
(default, 'Luettgen, Frami and Smith', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '7am-11am', 103),
(default, 'Wisozk-Shanahan', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2pm-3am', 104),
(default, 'Bailey, Little and West', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '10am - 10pm', 105),
(default, 'Feeney, Goyette and Leffler', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '12pm-10pm', 106),
(default, 'Parker-Mills', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '12am-8am', 107),
(default, 'Koss, Fisher and Hyatt', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2pm-3am', 108),
(default, 'Mills Tavern', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2pm-3am', 109),
(default, 'Spencer, Barrows and Haley', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '5pm-11:30pm', 110),
(default, 'Jerde-Berge', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '12pm-10pm', 111),
(default, 'Gusikowski and Daughters Grill', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '7am-11am', 112),
(default, 'Funk, Jacobi and Lebsack', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '4am - 8pm', 113),
(default, 'Ledner Cafe', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '7am-11am', 114),
(default, 'Wolf Cafe', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '1pm-3am', 115),
(default, 'Harvey Cafe', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '8am-11:59am', 116),
(default, 'Christiansen-Welch', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '12:30pm-11:30pm', 117),
(default, 'Price and Daughters Grill', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '5pm-11:30pm', 118),
(default, 'Von, Torphy and Collins', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis.', '7pm-7am', 119),
(default, 'Lind-Hermann', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '6am-11:30am', 120),
(default, 'Kertzmann-Breitenberg', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '5pm-11:30pm', 121),
(default, 'Keeling-Hudson', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '8am-11:59am', 122),
(default, 'Mayer and Daughters Grill', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '7am-11am', 123),
(default, 'Bernhard-Gutkowski', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '6am-11:30am', 124),
(default, 'Gulgowski Tavern', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2am - 6pm', 125),
(default, 'Lubowitz Diner', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '9am - 9pm', 126),
(default, 'Anderson Diner', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '11am - 9pm', 127),
(default, 'Kunze, Wuckert and Murray', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '12pm-11:59pm', 128),
(default, 'Cruickshank-Botsford', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '4am - 8pm', 129),
(default, 'Murazik, Aufderhar and Monahan', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '1pm-3pm', 130),
(default, 'Bogan-Goodwin', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '8am-11:59am', 131),
(default, 'Morar, Keeling and Ward', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '5pm-11am', 132),
(default, 'O''Kon-Feil', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '9am - 9pm', 133),
(default, 'Schumm Cafe', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '8am-11:59am', 134),
(default, 'McKenzie-Kozey', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '1pm-3pm', 135),
(default, 'Schuster Cafe', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '5pm-11:30pm', 136),
(default, 'Cummerata Diner', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '9am - 9pm', 137),
(default, 'Hane Bistro', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '12am-8am', 138),
(default, 'Koss, Watsica and Toy', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '5pm-11:30pm', 139),
(default, 'Weimann, Grady and Fisher', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '12pm-11:59pm', 140),
(default, 'Larkin-Schuppe', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '12:30pm-11:30pm', 141),
(default, 'Grant, Legros and Davis', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '11am - 9pm', 142),
(default, 'Bradtke, Moen and Shanahan', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '1pm-3pm', 143),
(default, 'Predovic-Abernathy', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '3pm-1am', 144),
(default, 'Trantow-Gottlieb', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '7am-11am', 145),
(default, 'Pagac, Dicki and Mayer', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '12pm-10pm', 146),
(default, 'Jacobi-Turcotte', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '11am - 9pm', 147),
(default, 'Padberg, Corwin and Jerde', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2pm-3am', 148),
(default, 'Wisozk-Jacobs', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '10am - 10pm', 149),
(default, 'Fadel, Weissnat and Muller', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '12pm-10pm', 150),
(default, 'Hermiston-Daniel', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '5pm-11am', 151),
(default, 'Nikolaus, Green and Fadel', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '7am-11am', 152),
(default, 'Lebsack Cafe', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '12pm-11:59pm', 153),
(default, 'Conn-Mueller', 'Fusce consequat. Nulla nisl. Nunc nisl.', '7am-11am', 154),
(default, 'Kris, Wunsch and Ledner', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '8am-11:59am', 155),
(default, 'Torp-Quitzon', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '12:30pm-11:30pm', 156),
(default, 'Durgan Cafe', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '12pm-10pm', 157),
(default, 'Sporer-Tillman', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '12pm-10pm', 158),
(default, 'Hills-Emard', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '5pm-11:30pm', 159),
(default, 'Larson Diner', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '7am-11am', 160),
(default, 'Lowe-Quigley', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '9am - 9pm', 161),
(default, 'Crona, Huels and Will', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '10am - 10pm', 162),
(default, 'Walsh Tavern', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '12pm-10pm', 163),
(default, 'Grimes, Huels and McGlynn', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '7pm-7am', 164),
(default, 'Hamill-Hudson', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '6am-11:30am', 165),
(default, 'Adams-Macejkovic', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '11am - 9pm', 166),
(default, 'Sipes Tavern', 'Fusce consequat. Nulla nisl. Nunc nisl.', '12am-8am', 167),
(default, 'O''Conner, Konopelski and Barton', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '10am - 10pm', 168),
(default, 'Waelchi-Mante', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis.', '5pm-11:30pm', 169),
(default, 'Muller, Marquardt and Jakubowski', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '5pm-11:30pm', 170),
(default, 'Volkman, Carter and Fadel', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '4am - 8pm', 171),
(default, 'Blanda Cafe', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2pm-3am', 172),
(default, 'Dare, Carter and Green', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '10am - 10pm', 173),
(default, 'Rohan, Roberts and Gusikowski', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '6am-11:30am', 174),
(default, 'Koch, Cole and Feest', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '12pm-10pm', 175),
(default, 'Spinka, Berge and Becker', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '1pm-3pm', 176),
(default, 'Ruecker-Haag', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '1pm-3pm', 177),
(default, 'Koelpin Bistro', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '4am - 8pm', 178),
(default, 'Kunze-Collier', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '6am-11:30am', 179),
(default, 'Nader Cafe', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '5pm-11:30pm', 180),
(default, 'Renner, Jacobson and Hermiston', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '7am-11am', 181),
(default, 'Paucek Tavern', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '7pm-7am', 182),
(default, 'Greenfelder, Kovacek and Tromp', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis.', '7am-11am', 183),
(default, 'Greenfelder Tavern', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '1pm-3am', 184),
(default, 'Kautzer Coffee Shop', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '3pm-1am', 185),
(default, 'Kreiger Tavern', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '7pm-7am', 186),
(default, 'Graham-Kuphal', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '3pm-1am', 187),
(default, 'Spinka Diner', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '12am-8am', 188),
(default, 'Kuvalis Tavern', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '4am - 8pm', 189),
(default, 'Fisher-Will', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.', '1pm-3am', 190),
(default, 'Mohr-Hills', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.', '12pm-11:59pm', 191),
(default, 'Keebler Tavern', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '12am-8am', 192),
(default, 'Goodwin Tavern', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '7am-11am', 193),
(default, 'Willms-Denesik', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '3pm-1am', 194),
(default, 'Wyman Coffee Shop', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '12:30pm-11:30pm', 195),
(default, 'Wisoky, Rosenbaum and Farrell', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '12pm-11:59pm', 196),
(default, 'Stokes, Ortiz and Jerde', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '9am - 9pm', 197),
(default, 'Kub-Cummerata', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2am - 6pm', 198),
(default, 'Bechtelar Cafe', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '9am - 9pm', 199),
(default, 'Boehm Tavern', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '9am - 9pm', 200);
