INSERT INTO Address (street, address_line_2, city, state) VALUES
('123 Main St', NULL, 'Anytown', 'CA'),
('456 Elm St', 'Apt 101', 'Sometown', 'NY'),
('789 Oak St', NULL, 'Othertown', 'TX'),
('111 Pine St', 'Suite 5', 'Yourtown', 'FL'),
('222 Maple St', NULL, 'Smalltown', 'WA'),
('333 Cedar St', 'Unit B', 'Theirtown', 'IL'),
('444 Birch St', 'Floor 3', 'Hometown', 'GA'),
('555 Walnut St', NULL, 'Anothertown', 'MI'),
('666 Spruce St', 'Building C', 'Somewhere', 'OH'),
('777 Ash St', NULL, 'Nowhere', 'PA'),
('888 Chestnut St', 'Unit 7', 'Everywhere', 'MA'),
('999 Fir St', NULL, 'Otherwhere', 'CO'),
('1010 Sycamore St', 'Suite 12', 'Anyplace', 'NC'),
('1212 Poplar St', NULL, 'Newtown', 'AZ'),
('1313 Pineapple St', 'Floor 4', 'Randomtown', 'NV'),
('1414 Orange St', 'Unit 3A', 'Differenttown', 'LA'),
('1515 Lemon St', NULL, 'Unknowntown', 'VA'),
('1616 Lime St', 'Apt 205', 'Middletown', 'MO'),
('1717 Grape St', NULL, 'Sometowntwo', 'WI'),
('1818 Cherry St', 'Building E', 'Othertowntwo', 'OK'),
('1919 Banana St', 'Suite 9', 'Overthere', 'AL'),
('2020 Apple St', NULL, 'Nowheretwo', 'OR'),
('2121 Peach St', 'Floor 1', 'Heretown', 'TN'),
('2222 Pear St', NULL, 'Thistown', 'UT'),
('2323 Plum St', 'Unit 20', 'Thatplace', 'ID'),
('2424 Blueberry St', NULL, 'Hereandthere', 'NE'),
('2525 Raspberry St', 'Suite 8', 'Anywheretown', 'KS'),
('2626 Blackberry St', 'Apt 301', 'Everywheretown', 'IA'),
('2727 Strawberry St', NULL, 'Somewheretown', 'AR'),
('2828 Cranberry St', 'Building F', 'Overtheretown', 'NH'),
('2929 Watermelon St', NULL, 'Somewheretwo', 'MS'),
('3030 Cantaloupe St', 'Floor 2', 'Anotherplace', 'WY'),
('3131 Honeydew St', NULL, 'Otherplacetwo', 'NM'),
('3232 Kiwi St', 'Unit 15', 'Nowherethree', 'MT'),
('3333 Mango St', NULL, 'Somewherethree', 'SD'),
('3434 Papaya St', 'Apt 101', 'Lastplace', 'ND'),
('3535 Pine St', NULL, 'Endtown', 'RI'),
('3636 Oak St', 'Building G', 'Startingtown', 'CT'),
('3737 Elm St', NULL, 'Ontown', 'MD'),
('3838 Maple St', 'Suite 10', 'Undertown', 'DE'),
('3939 Cedar St', NULL, 'Thistownthree', 'VT'),
('4040 Birch St', 'Floor 5', 'Thatplacefour', 'HI'),
('4141 Walnut St', NULL, 'Overhere', 'DC'),
('4242 Spruce St', 'Unit 25', 'Overthere', 'WV'),
('4343 Ash St', NULL, 'Anothertownfive', 'ME'),
('4444 Chestnut St', 'Building H', 'Heretwo', 'NH'),
('4545 Fir St', NULL, 'Overtherefive', 'ID'),
('4646 Sycamore St', 'Suite 18', 'Nowhereseven', 'NE'),
('4747 Poplar St', NULL, 'Thistowneight', 'WY'),
('4848 Pineapple St', 'Floor 6', 'Overherenine', 'KS'),
('4949 Orange St', NULL, 'Overthereeight', 'IA'),
('5050 Lemon St', 'Apt 401', 'Anothertownnine', 'AR');
