INSERT INTO MenuItem (name, menu_type) VALUES
('Cheeseburger', 'Burgers'),
('Caesar Salad', 'Salads'),
('Margherita Pizza', 'Pizzas'),
('Chocolate Cake', 'Desserts'),
('Iced Tea', 'Beverages'),
('French Fries', 'Appetizers'),
('Spaghetti Bolognese', 'Pasta'),
('Greek Salad', 'Salads'),
('BBQ Ribs', 'Entrees'),
('Tiramisu', 'Desserts'),
('Lemonade', 'Beverages'),
('Onion Rings', 'Appetizers'),
('Sushi Platter', 'Sushi'),
('Caprese Salad', 'Salads'),
('Steak', 'Entrees'),
('Apple Pie', 'Desserts'),
('Cappuccino', 'Beverages'),
('Mozzarella Sticks', 'Appetizers'),
('Fish and Chips', 'Seafood'),
('Chicken Alfredo', 'Pasta'),
('Nachos', 'Appetizers'),
('Pasta Primavera', 'Pasta'),
('Fruit Salad', 'Salads'),
('Hot Dog', 'Sandwiches'),
('Club Sandwich', 'Sandwiches'),
('Pancakes', 'Breakfast'),
('Milkshake', 'Beverages'),
('Garlic Bread', 'Appetizers'),
('Shrimp Scampi', 'Seafood'),
('Cobb Salad', 'Salads'),
('Tacos', 'Mexican'),
('Lasagna', 'Pasta'),
('Brownie Sundae', 'Desserts'),
('Espresso', 'Beverages'),
('Buffalo Wings', 'Appetizers'),
('Vegetable Stir Fry', 'Vegetarian'),
('Ice Cream Cone', 'Desserts'),
('Lobster Roll', 'Seafood'),
('Margarita', 'Beverages'),
('Beef Stir Fry', 'Meat'),
('Fried Chicken', 'Chicken'),
('Fajitas', 'Mexican'),
('Pad Thai', 'Asian'),
('Cheesecake', 'Desserts'),
('Mimosa', 'Beverages'),
('Veggie Burger', 'Vegetarian'),
('Clam Chowder', 'Soups'),
('Churros', 'Desserts'),
('Cinnamon Roll', 'Breakfast'),
('Fried Rice', 'Asian'),
('Garden Salad', 'Salads'),
('Hamburger', 'Burgers'),
('Pesto Pasta', 'Pasta'),
('Donuts', 'Desserts'),
('Eggplant Parmesan', 'Vegetarian'),
('Green Tea', 'Beverages'),
('Quesadilla', 'Mexican'),
('Macaroni and Cheese', 'Pasta'),
('Tuna Salad', 'Salads'),
('Hot Chocolate', 'Beverages'),
('Pho', 'Asian'),
('Soda', 'Beverages'),
('Ramen', 'Asian'),
('Waffles', 'Breakfast'),
('Pulled Pork Sandwich', 'Sandwiches'),
('Croissant', 'Breakfast'),
('Mussels', 'Seafood'),
('Baklava', 'Desserts'),
('Arnold Palmer', 'Beverages'),
('Caramel Popcorn', 'Snacks'),
('Biscuits and Gravy', 'Breakfast'),
('Poke Bowl', 'Asian'),
('Key Lime Pie', 'Desserts'),
('Bubble Tea', 'Beverages'),
('Chicken Caesar Wrap', 'Sandwiches'),
('Smoothie', 'Beverages'),
('Calamari', 'Seafood'),
('Guacamole', 'Mexican'),
('French Toast', 'Breakfast'),
('Chili', 'Soups'),
('Salmon and Asparagus Foil Packets','Entrees'),
('Caprese Pesto Stuffed Chicken','Entrees'),
('Caprese Chicken Sandwich','Entrees'),
('Vegetable Paella','Entrees'),
('Maple Dijon Glazed Pork Tenderloin','Entrees'),
('Chimichurri Marinated Grilled Steak','Entrees'),
('Shrimp and Andouille Sausage Jambalaya','Entrees'),
('Chicken Enchiladas with Green Chili Sauce','Entrees'),
('Spicy Cajun Shrimp Pasta','Entrees'),
('Roasted Red Pepper and Goat Cheese Stuffed Chicken','Entrees');
