insert into PromotionalEvent (restaurant_id, admin_id, description) values (7, 10, 'integer pede justo lacinia eget tincidunt eget');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (3, 41, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (16, 3, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (13, 34, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (41, 55, 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (18, 35, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (32, 6, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (33, 5, 'massa donec dapibus duis at velit eu');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (30, 46, 'odio odio elementum eu interdum eu tincidunt in');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (33, 42, 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (43, 4, 'id mauris vulputate elementum nullam varius');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (41, 51, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (7, 31, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (11, 10, 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (50, 15, 'purus aliquet at feugiat non pretium');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (10, 30, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (48, 39, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (36, 43, 'orci vehicula condimentum curabitur in libero ut massa volutpat');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (12, 33, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (36, 5, 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (45, 25, 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (45, 35, 'eleifend pede libero quis orci');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (44, 33, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (32, 62, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (29, 21, 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (41, 47, 'sapien cum sociis natoque penatibus et magnis dis parturient');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (43, 38, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (9, 21, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (9, 65, 'suscipit nulla elit ac nulla sed vel enim sit');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (18, 7, 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (42, 59, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (34, 62, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (50, 51, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (11, 60, 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (16, 64, 'mollis molestie lorem quisque ut erat curabitur');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (39, 23, 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (25, 58, 'semper porta volutpat quam pede lobortis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (8, 5, 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (45, 27, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (2, 28, 'odio cras mi pede malesuada');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (39, 14, 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (1, 53, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (49, 17, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (24, 43, 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (9, 24, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (15, 44, 'ultrices posuere cubilia curae nulla dapibus dolor');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (6, 51, 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (44, 25, 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (39, 61, 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (33, 35, 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (45, 60, 'duis aliquam convallis nunc proin at turpis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (10, 10, 'rutrum ac lobortis vel dapibus at');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (27, 1, 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (13, 65, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (34, 8, 'est congue elementum in hac habitasse');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (22, 29, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (50, 17, 'ut nunc vestibulum ante ipsum primis in faucibus orci');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (47, 49, 'ut at dolor quis odio consequat varius integer ac leo pellentesque');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (45, 2, 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (15, 25, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (41, 19, 'feugiat non pretium quis lectus suspendisse');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (7, 65, 'fusce lacus purus aliquet at feugiat non');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (15, 13, 'non sodales sed tincidunt eu felis fusce posuere felis sed');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (26, 6, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (23, 8, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (27, 60, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (44, 31, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (28, 22, 'elit sodales scelerisque mauris sit');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (31, 16, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (20, 32, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (22, 47, 'ut erat curabitur gravida nisi at nibh in');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (37, 43, 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (3, 9, 'ut nulla sed accumsan felis');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (41, 24, 'ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (30, 58, 'sapien cursus vestibulum proin eu mi');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (2, 50, 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (29, 51, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (18, 14, 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (37, 51, 'lectus aliquam sit amet diam');
insert into PromotionalEvent (restaurant_id, admin_id, description) values (49, 39, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla');
