-- Additional 50 Restaurant table rows (sample data based on Address table)
INSERT INTO Restaurant (restaurant_name, description, hours, address) VALUES
('Mamas Kitchen', 'Homestyle cooking at its best!', 'Mon-Sat: 8am-9pm, Sun: 9am-8pm', 2),
('Pasta Paradise', 'Italian delicacies served daily.', 'Mon-Fri: 11:30am-10pm, Sat-Sun: 12pm-9pm', 7),
('Brew Haven', 'Craft beers and good times!', 'Mon-Sat: 4pm-12am, Sun: 2pm-10pm', 12),
('Garden Grille', 'Fresh and organic farm-to-table meals.', 'Daily: 10am-8pm', 17),
('The Pancake Place', 'Fluffy pancakes for breakfast enthusiasts.', 'Mon-Sun: 7am-3pm', 22),
('Fiesta Mexicana', 'Authentic Mexican cuisine.', 'Tue-Sun: 11am-10pm', 27),
('Bella Napoli', 'Savor the taste of Naples.', 'Daily: 12pm-11pm', 32),
('The Noodle House', 'Noodles from all around the world!', 'Mon-Sat: 11am-9pm, Sun: 12pm-8pm', 37),
('Smokehouse BBQ', 'Slow-smoked barbecue goodness.', 'Wed-Sun: 12pm-9pm', 42),
('Fisherman’s Catch', 'Fresh seafood served with a view.', 'Daily: 11:30am-10pm', 47),
('Veggie Delight', 'A haven for vegetarian delights.', 'Mon-Sun: 10am-7pm', 3),
('The Steakhouse', 'Juicy steaks cooked to perfection.', 'Tue-Sat: 5pm-10pm', 8),
('The Curry Pot', 'Spice up your day with flavorful curries.', 'Mon-Sun: 11:30am-9:30pm', 13),
('Sip & Savor Café', 'Where every sip and bite delights!', 'Mon-Fri: 8am-7pm, Sat-Sun: 9am-5pm', 18),
('Burger Joint', 'Serving classic burgers since 1985.', 'Mon-Sun: 11am-10pm', 23),
('Tropical Taste', 'Island-inspired dishes for a tropical vibe.', 'Wed-Sun: 12pm-8pm', 28),
('Slice of Heaven', 'Every slice is a taste of heaven!', 'Daily: 11am-9pm', 33),
('Café Parisienne', 'Bonjour! French cuisine at its finest.', 'Tue-Sun: 10am-10pm', 38),
('Wrap It Up', 'Wraps and rolls for on-the-go meals.', 'Mon-Fri: 10am-6pm, Sat: 11am-5pm', 43),
('Diner Deluxe', 'Classic diner fare with a modern twist.', 'Mon-Sun: 7am-10pm', 48),
('Ramen House', 'Slurp-worthy bowls of authentic ramen.', 'Tue-Sat: 11:30am-10pm, Sun: 12pm-9pm', 4),
('Tandoori Nights', 'Tantalizing tandoori flavors.', 'Mon-Sun: 12pm-11pm', 9),
('Crispy Crust Pizzeria', 'Crunchy crusts and savory toppings!', 'Mon-Sun: 11am-10pm', 14),
('Tea Time Corner', 'A cozy spot for tea enthusiasts.', 'Mon-Fri: 9am-6pm, Sat-Sun: 10am-4pm', 19),
('Nacho Nation', 'Where nachos reign supreme!', 'Mon-Sat: 12pm-11pm, Sun: 1pm-9pm', 24),
('Sushi Sensation', 'Sensational sushi rolls for every taste.', 'Tue-Sun: 11:30am-10pm', 29),
('BBQ Pitstop', 'Fueling your barbecue cravings!', 'Wed-Sun: 12pm-8pm', 34),
('Wok Wonders', 'Wok-tossed wonders from Asia.', 'Mon-Sat: 11am-9pm, Sun: 12pm-7pm', 39),
('Pita Palace', 'Freshly baked pitas filled with goodness.', 'Mon-Sun: 10am-8pm', 44),
('Soup Spoon', 'Comfort in a bowl - soups for every soul.', 'Mon-Fri: 11am-7pm, Sat: 12pm-5pm', 49),
('Pancake Pantry', 'A pantry full of pancake delights.', 'Mon-Sun: 7am-4pm', 5),
('Taste of Thailand', 'Journey through the flavors of Thailand.', 'Tue-Sun: 12pm-10pm', 10),
('Bakery Bliss', 'Freshly baked goodness every day!', 'Mon-Sun: 8am-6pm', 15),
('Tempting Tacos', 'Tantalizing tacos in every variety.', 'Mon-Sat: 11am-10pm, Sun: 12pm-9pm', 20),
('Smoothie Shack', 'Blend of health and deliciousness!', 'Mon-Sun: 9am-8pm', 25),
('Café Roma', 'Italian café with a charming ambiance.', 'Tue-Sun: 9am-11pm', 30),
('Cheeseburger Paradise', 'Where cheeseburgers rule!', 'Mon-Sun: 11am-9pm', 35),
('Rice n Spice', 'A fusion of rice and spice!', 'Mon-Sat: 12pm-10pm, Sun: 1pm-9pm', 40),
('Taste of India', 'A diverse palette of Indian flavors.', 'Tue-Sun: 11:30am-10pm', 45),
('Bagel Bliss', 'Every bagel-lover’s paradise.', 'Mon-Sun: 6am-4pm', 50),
('Chopstick Charm', 'Chinese delicacies to charm your taste buds.', 'Mon-Sat: 11am-9pm, Sun: 12pm-8pm', 6),
('Taco Time', 'Tacos for any time of the day!', 'Mon-Sun: 10am-8pm', 11),
('Café Mocha', 'Where coffee meets delight!', 'Mon-Fri: 7am-8pm, Sat-Sun: 8am-6pm', 16),
('Hot Dog Haven', 'A paradise for hot dog enthusiasts.', 'Mon-Sun: 11am-7pm', 21),
('Sizzle n Spice', 'Where sizzle meets spice!', 'Tue-Sun: 12pm-11pm', 26),
('The Spice Emporium', 'A culinary journey through spices!', 'Tue-Sun: 12pm-10pm', 1),
('Sushi Central', 'Fresh sushi served daily.', 'Mon-Sat: 11:30am-9pm, Sun: 12pm-8pm', 31),
('Taco Haven', 'Tacos for every mood!', 'Mon-Fri: 10am-8pm, Sat-Sun: 11am-9pm', 36),
('Mamma Mia Pizzeria', 'Authentic Italian pizzas made with love.', 'Daily: 11am-10pm', 41),
('The Green Bowl', 'Healthy bowls for a nutritious meal!', 'Mon-Sun: 9am-7pm', 46);
